net_name: 'TransUNet'
train_dir: '/data/jzw/data/LiTS/fixed_data' # '/home/jzw/data/LiTS/fixed_data/'
# train_list: '/data/jzw/workspace_seg/template_jzw/datatxt/LitsSeg_train.txt'
test_dir: '/data/jzw/data/LiTS/fixed_data'
# test_list: '/data/jzw/workspace_seg/template_jzw/datatxt/LitsSeg_test.txt'
## depth in CT 
# depth: 24
frame_num: 1

## continue train
continue_train_timestamp: ''
continue_train_epoch: 0
pretrain_model: ''
# continue_train_timestamp: '2021-10-22-08-29-24'
# continue_train_epoch: 64
# pretrain_model: '/data/jzw/workspace/lits_3d/runs/lits_myself/unet3d/train/2021-10-22-08-29-24/checkpoints/epoch_64.pth'

## evaluate model
resume_model: '' #'runs/lits_seg/unet/train/2021-09-16-22-20-37/checkpoints/epoch_100_model_best_loss.pth'

input_height: 224
input_width: 224

train_epoch : 100
save_every_epoch : 1
early_stop: 20
# change the batchsize on each GPU
batch_size: 1
print_freq : 100
last_iter : -1 
augment: True
sync: True
# train_output_directory: 'checkpoints/LitsSeg/UNet' # checkout save state_dict
# log_directory: 'logs/LitsSeg/UNet' # summery writer
running_root: 'runs/lits_myself/transunet'
# checkpoint_directory: 'checkpoints/LitsSeg/UNet'
# summary_directory: 'summarys/LitsSeg/UNet'
# savedir: 'checkpoints/save'

bn: 'sync'

model:
  in_channels: 1
  out_channels: 2


optimizer:
  type: 'adam'
  
lr_scheduler:
  base_lr: 0.001
  type: STEP                  #or COSINE
  gamma: 0.1                  #default for STEP
  verbose: False               #default for STEP
  step_size: 60              #default for STEP
  last_epoch: -1       

loss:
  type: 'bcel' #'focal' 
  # kwargs:
  #   class_num: 2

thr: 0.55
